name: docker-compose

services:
  nginx:
    container_name: nginx

    build:
      tags:
        - nginx:latest
      context: ./nginx
      dockerfile: Dockerfile

    ports:
      - "80:80"
      - "443:443"

    environment:
      - WEB_SERVER_HOST=host.docker.internal
      - WEB_SERVER_PORT=26802
