name: Tests

on:
  push:
    paths-ignore:
      - ".vscode/**"
      - ".github/**"
      - ".gitignore"
      - "compose.yaml"
      - "LICENSE"
      - "README.md"
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install poetry
        run: pip install --upgrade poetry && poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run tests
        run: pytest
